apiVersion: v1
kind: ConfigMap
metadata:
  name: job-magnet-backend-config
  namespace: job-magnet
data:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-host:3306/job_portal?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
