apiVersion: v1
kind: Secret
metadata:
  name: job-magnet-backend-secrets
  namespace: job-magnet
type: Opaque
stringData:
  DB_USERNAME: replace_me
  DB_PASSWORD: replace_me
  JWT_SECRET: replace_me_with_32+_chars
  SPRING_SECURITY_USER: replace_me
  SPRING_SECURITY_PASSWORD: replace_me
  MAIL_USERNAME: replace_me
  MAIL_PASSWORD: replace_me
