apiVersion: v1
kind: Secret
metadata:
  name: job-magnet-backend-secrets
  namespace: job-magnet
type: Opaque
stringData:
  DB_USERNAME: root
  DB_PASSWORD: "200033400410"
  JWT_SECRET: replace-with-a-long-32+char-secret-key-123456
  SPRING_SECURITY_USER: admin
  SPRING_SECURITY_PASSWORD: admin123
  MAIL_USERNAME: aa@gmail.com
  MAIL_PASSWORD: bnndepaziafykcnr