apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-magnet-frontend
  namespace: job-magnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-magnet-frontend
  template:
    metadata:
      labels:
        app: job-magnet-frontend
    spec:
      containers:
        - name: frontend
          image: e20376/job-magnet-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
