apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: job-magnet-ingress
  namespace: job-magnet
spec:
  ingressClassName: nginx
  rules:
    - host: job-magnet.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: job-magnet-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: job-magnet-frontend
                port:
                  number: 80
